/**
 * POST /api/ai/advisor — "what should I sow this season?"
 *
 * Takes the farmer's province, land size, soil type, season and budget and
 * returns a ranked crop shortlist with reasoning, sowing windows, seed rates,
 * fertiliser plans and risks — generated by Gemini against the hand-written
 * planning prompt in `lib/prompts/advisor.ts`.
 *
 * Deliberately does NOT forecast profit: the model has no live price data, and
 * the project contract bans presenting invented figures as real. Cost and yield
 * come back as clearly-labelled estimates only.
 *
 * Auth is optional; a signed-in farmer's saved profile fills in anything the
 * request leaves out.
 */

import { ok, fail, handler, readJson } from "@/lib/api-helpers"
import { extractJson, generateText } from "@/lib/services/geminiService"
import {
  buildAdvisorSystemPrompt,
  buildAdvisorUserPrompt,
  currentSeason,
  PAKISTAN_PROVINCES,
} from "@/lib/prompts"
import { aiFailure, cleanText, optionalAuth, requireGemini, resolveLanguage, toFarmerProfile } from "../_shared"

export const dynamic = "force-dynamic"
// Runtime budget: `vercel.json` grants `app/api/ai/**` a 60s maxDuration, which a
// 6144-token planning call with a thinking budget needs to finish.

/** Up to five full crop plans plus the model's own reasoning tokens. */
const MAX_OUTPUT_TOKENS = 6144

/**
 * Maps the many spellings the UI and older data use onto the canonical province
 * names. Unrecognised input is passed through verbatim with `recognised: false`
 * so the model can still work with it; the prompt's Pakistan grounding is what
 * stops a non-Pakistani place name producing non-Pakistani agronomy.
 */
const PROVINCE_ALIASES: Record<string, string> = {
  punjab: "Punjab",
  sindh: "Sindh",
  sind: "Sindh",
  kpk: "Khyber Pakhtunkhwa",
  kp: "Khyber Pakhtunkhwa",
  "khyber pakhtunkhwa": "Khyber Pakhtunkhwa",
  "khyber-pakhtunkhwa": "Khyber Pakhtunkhwa",
  nwfp: "Khyber Pakhtunkhwa",
  balochistan: "Balochistan",
  baluchistan: "Balochistan",
  "gilgit-baltistan": "Gilgit-Baltistan",
  "gilgit baltistan": "Gilgit-Baltistan",
  gb: "Gilgit-Baltistan",
  ajk: "Azad Jammu & Kashmir",
  "azad kashmir": "Azad Jammu & Kashmir",
  "azad jammu & kashmir": "Azad Jammu & Kashmir",
  "azad jammu and kashmir": "Azad Jammu & Kashmir",
  islamabad: "Islamabad Capital Territory",
  ict: "Islamabad Capital Territory",
  "islamabad capital territory": "Islamabad Capital Territory",
}

/**
 * The substring match below needs a floor. Without one, a one- or two-character
 * input matches almost anything ("b" is inside "Punjab"), so a typo would
 * silently produce confident Punjab-specific advice for a farmer who never said
 * Punjab — exactly the "never default to one place" failure the contract bans.
 */
const MIN_FUZZY_PROVINCE_CHARS = 4

function normaliseProvince(input: string): { province: string; recognised: boolean } {
  const key = input.trim().toLowerCase()
  if (!key) return { province: "", recognised: false }
  const mapped = PROVINCE_ALIASES[key]
  if (mapped) return { province: mapped, recognised: true }
  if (key.length >= MIN_FUZZY_PROVINCE_CHARS) {
    const partial = PAKISTAN_PROVINCES.find((p) => p.toLowerCase().includes(key) || key.includes(p.toLowerCase()))
    if (partial) return { province: partial, recognised: true }
  }
  return { province: input.trim(), recognised: false }
}

function normaliseSeason(input: unknown, now: Date): { season: "rabi" | "kharif"; inferred: boolean } {
  const value = String(input ?? "").trim().toLowerCase()
  if (value === "rabi" || value === "winter") return { season: "rabi", inferred: false }
  if (value === "kharif" || value === "summer" || value === "monsoon") return { season: "kharif", inferred: false }
  return { season: currentSeason(now), inferred: true }
}

function toNumber(value: unknown): number | undefined {
  if (typeof value === "number" && Number.isFinite(value)) return value
  if (typeof value === "string") {
    const parsed = Number(value.replace(/[, ]/g, "").replace(/[^0-9.]/g, ""))
    if (Number.isFinite(parsed) && parsed > 0) return parsed
  }
  return undefined
}

function stringList(value: unknown, max: number): string[] {
  if (!Array.isArray(value)) return typeof value === "string" && value.trim() ? [value.trim()] : []
  return value.map((v) => (typeof v === "string" ? v.trim() : "")).filter(Boolean).slice(0, max)
}

/** Shapes the model output into the response contract. */
function normaliseRecommendations(parsed: any) {
  const list = Array.isArray(parsed?.recommendations) ? parsed.recommendations : []
  return list.slice(0, 6).map((item: any, index: number) => ({
    rank: Number(item?.rank) || index + 1,
    crop: cleanText(item?.crop, 80) || "Unnamed crop",
    localName: cleanText(item?.localName, 80) || null,
    suitabilityScore: Math.max(0, Math.min(100, Math.round(Number(item?.suitabilityScore) || 0))),
    riskLevel: ["low", "medium", "high"].includes(String(item?.riskLevel).toLowerCase())
      ? String(item.riskLevel).toLowerCase()
      : "medium",
    whyThisCrop: cleanText(item?.whyThisCrop ?? item?.reasoning, 800) || null,
    sowingWindow: cleanText(item?.sowingWindow, 200) || null,
    varieties: stringList(item?.varieties, 6),
    seedRatePerAcre: cleanText(item?.seedRatePerAcre, 160) || null,
    waterRequirement: ["low", "medium", "high"].includes(String(item?.waterRequirement).toLowerCase())
      ? String(item.waterRequirement).toLowerCase()
      : null,
    irrigations: cleanText(item?.irrigations, 200) || null,
    fertiliserPlan: cleanText(item?.fertiliserPlan ?? item?.fertilizerPlan, 600) || null,
    estimatedInputCostPerAcrePKR: cleanText(item?.estimatedInputCostPerAcrePKR, 160) || null,
    expectedYieldPerAcre: cleanText(item?.expectedYieldPerAcre, 160) || null,
    durationDays: toNumber(item?.durationDays) ?? null,
    marketNote: cleanText(item?.marketNote, 400) || null,
    risks: stringList(item?.risks, 4),
    keyPractices: stringList(item?.keyPractices, 5),
  }))
}

export const POST = handler(async (req: Request) => {
  const notConfigured = requireGemini()
  if (notConfigured) return notConfigured

  const body = await readJson(req)
  const now = new Date()

  const user = await optionalAuth(req)
  const profile = toFarmerProfile(user)

  const provinceInput = cleanText(body.province ?? body.state, 80) || profile?.province || ""
  const { province, recognised } = normaliseProvince(provinceInput)

  if (!province) {
    return fail(
      "Please tell us your province so the advice fits your area (Punjab, Sindh, Khyber Pakhtunkhwa, Balochistan, Gilgit-Baltistan, Azad Jammu & Kashmir or Islamabad Capital Territory).",
      400,
    )
  }

  const landSizeAcres = toNumber(body.landSize ?? body.landSizeAcres ?? body.acres) ?? profile?.landSizeAcres
  const soilType = cleanText(body.soilType ?? body.soil, 60) || profile?.soilType || ""
  const budgetPKR = toNumber(body.budget ?? body.budgetPKR)
  const { season, inferred } = normaliseSeason(body.season, now)

  const district = cleanText(body.district, 80) || profile?.district || ""
  const waterSource = cleanText(body.waterSource ?? body.irrigation ?? body.irrigationType, 80) || profile?.waterSource || ""
  const previousCrop = cleanText(body.previousCrop ?? body.lastCrop, 80)
  const goal = cleanText(body.goal ?? body.objective, 300)
  const language = resolveLanguage(body.language, goal, user?.preferredLanguage)

  const options = {
    province,
    district,
    landSizeAcres,
    soilType,
    season,
    budgetPKR,
    waterSource,
    previousCrop,
    goal,
    language,
    profile,
    now,
  }

  let result
  try {
    result = await generateText({
      system: buildAdvisorSystemPrompt(options),
      prompt: buildAdvisorUserPrompt(options),
      maxOutputTokens: MAX_OUTPUT_TOKENS,
      temperature: 0.45,
      thinkingBudget: 1024,
      json: true,
    })
  } catch (error) {
    return aiFailure(error)
  }

  const parsed = extractJson<any>(result.text)

  if (!parsed) {
    // Never 500 on an unparseable answer — hand back the prose instead.
    return ok({
      parsed: false,
      model: result.model,
      season,
      province,
      rawAdvice: result.text,
      message: "The recommendations could not be structured. The AI's notes are included as text.",
    })
  }

  const recommendations = normaliseRecommendations(parsed)
  if (!recommendations.length) {
    return ok({
      parsed: false,
      model: result.model,
      season,
      province,
      rawAdvice: result.text,
      message: "The AI did not return any usable crop recommendations. Please try again.",
    })
  }

  return ok({
    parsed: true,
    province,
    provinceRecognised: recognised,
    district: district || null,
    season,
    seasonInferred: inferred,
    seasonWindowNote: cleanText(parsed?.seasonWindowNote, 300) || null,
    landSizeAcres: landSizeAcres ?? null,
    soilType: soilType || null,
    budgetPKR: budgetPKR ?? null,
    recommendations,
    landAllocationPlan: cleanText(parsed?.landAllocationPlan, 1200) || null,
    budgetNote: cleanText(parsed?.budgetNote, 600) || null,
    generalAdvice: stringList(parsed?.generalAdvice, 5),
    warnings: stringList(parsed?.warnings, 5),
    nextSteps: stringList(parsed?.nextSteps, 4),
    missingInformation: stringList(parsed?.missingInformation, 5),
    confidence: ["low", "medium", "high"].includes(String(parsed?.confidence).toLowerCase())
      ? String(parsed.confidence).toLowerCase()
      : "medium",
    costsAreEstimates: true,
    disclaimer:
      "Costs and yields here are rough estimates, not live figures. Check today's market rate and input prices at your nearest mandi or dealer, and confirm the plan with your local agriculture extension officer before committing land.",
    language: language === "auto" ? "en" : language,
    model: result.model,
    truncated: result.truncated,
    authenticated: Boolean(user),
    usage: result.usage,
  })
})
